name: wakelock_windows
description: >-2
  Windows platform implementation of the wakelock_platform_interface for the wakelock plugin.
version: 0.2.2
repository: https://github.com/Alejandro-Gon/wakelock/tree/main/wakelock_windows

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  win32: ^5.3.0

  wakelock_platform_interface:
    git:
      url: https://github.com/Alejandro-Gon/wakelock.git
      ref: main
      path: wakelock_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

# todo: use dartPluginClass declaration once that lands on stable (https://github.com/flutter/flutter/issues/52267_
#flutter:
#  plugin:
#    platforms:
#      windows:
#        dartPluginClass: WakelockWindows
