name: wakelock_web
description: Web platform implementation of the wakelock_platform_interface for the wakelock plugin.
version: 0.4.1
repository: https://github.com/Alejandro-Gon/wakelock/tree/main/wakelock_web

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  js: ^0.6.3

  wakelock_platform_interface:
    git:
      url: https://github.com/Alejandro-Gon/wakelock.git
      ref: main
      path: wakelock_platform_interface 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  wakelock:
    path: ../wakelock

flutter:
  plugin:
    platforms:
      web:
        pluginClass: WakelockWeb
        fileName: wakelock_web.dart

  assets:
    - assets/no_sleep.js
